name: flutter_animate_on_scroll
description: A Flutter animation package to animate on scroll.
version: 0.0.1
homepage: https://github.com/FadiChaalab/flutter_animate_on_scroll

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
