name: flutter_animate_on_scroll
description: Introducing Flutter Animate on Scroll - a Flutter package for animating widgets based on scroll events. Effortlessly create captivating, interactive scroll-based animations to enhance your UI.
version: 0.1.0
homepage: https://github.com/FadiChaalab/flutter_animate_on_scroll

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
