name: flutter_animate_on_scroll
description: Introducing Flutter animate on scroll - a powerful Flutter animation package designed specifically for animating widgets based on scroll events. Flutter animate on scroll enables you to effortlessly create captivating and interactive scroll-based animations that bring your user interface to life.
version: 0.0.2
homepage: https://github.com/FadiChaalab/flutter_animate_on_scroll

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
